### ISSUE TITLE
Error when logging in user that doesn't exist

### ISSUE THREAD

**Issue by pproe** [PubMedConnections/PubMedConnections#4]
Service crashes when using username that doesn't exist. Need to add type check on user object when clearing `revoked_tokens`

```
Traceback (most recent call last):
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask_restx\api.py", line 671, in error_router
    return original_handler(f)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask_restx\api.py", line 669, in error_router
    return self.handle_error(e)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask_restx\api.py", line 671, in error_router
    return original_handler(f)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask_restx\api.py", line 669, in error_router
    return self.handle_error(e)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask_restx\api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\Users\Patrick\.conda\envs\pubmed-connections\Lib\site-packages\flask_restx\resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\Patrick\Documents\University\Design Project\PubMedConnections\app\api\auth.py", line 42, in post
    if authenticate_user(username, password):
  File "C:\Users\Patrick\Documents\University\Design Project\PubMedConnections\app\controller\user_controller.py", line 63, in authenticate_user
    clean_up_expired_tokens(username)
  File "C:\Users\Patrick\Documents\University\Design Project\PubMedConnections\app\controller\user_controller.py", line 32, in clean_up_expired_tokens
    revoked_tokens = json.loads(user['revoked_tokens'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Jai-C** [comment]
Resolved on Front-end branch commit c8881b5b3bded46c31a661e98a65fd2b9d1ed303
